### PR TITLE
add k8s

### PR DESCRIPTION
**Pull request by PedramNavid**
you data scientists were so preoccupied with wondering if you could you never stopped to think if you should

### CODE REVIEW

**Comment by PedramNavid** [comment]
@jwills hey buddy

**Comment by jwills** [comment]
@PedramNavid how did you get a github account? they don't give those out to just anybody

**Comment by matsonj** [comment]
Image from iOS (2)

**Comment by PedramNavid** [comment]
> @PedramNavid how did you get a github account? they don't give those out to just anybody

hidden perks of being a data influencer

**Comment by matsonj** [comment]
looks good, thanks!

(to be clear, the meme above is a self own not me harassing @PedramNavid)

**Comment by jwills** [comment]
> looks good, thanks!
> 
> (to be clear, the meme above is a self own not me harassing @PedramNavid)

I would prefer if it was you harassing pedram fwiw

**Comment by matsonj** [comment]
We only harass @tayloramurphy here

**Comment by jwills** [comment]
now I _know_ that guy isn't allowed to have a github account, what is going on

**Comment by Alex-Monahan** [comment]
> Image from iOS (2)

Chef's kiss...

**Pull request merged**
