### PR TITLE
uv install works now

### PR DESCRIPTION
**Pull request by mermelstein**

### CODE REVIEW

**Comment by matsonj** [comment]
@mermelstein not sure whats going on but invoking `uv pip install` isn’t working in the `make build` step.

```
uv pip install --system --no-cache -r requirements.txt
make: uv: No such file or directory
make: *** [Makefile:2: build] Error 127
```

**Comment by mermelstein** [comment]
aight can take a look at that step in a bit

**Comment by matsonj** [comment]
Dropping two links in here from my tl this AM.

https://dev.to/kummerer94/multi-stage-docker-builds-for-pyton-projects-using-uv-223g (h/t @PedramNavid)

https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container (h/t @davidgasquez )

I think I can do the latter option which should make `uv` available in the CI env. However, I think the `—system` flag may require elevated permissions that the container doesn’t have. But we can address that when we get there.

**Comment by matsonj** [comment]
```
error: Failed to install: rpds_py-0.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (rpds-py==0.18.0)
  Caused by: failed to create directory `/usr/local/lib/python3.10/dist-packages/rpds_py-0.18.0.dist-info`
  Caused by: Permission denied (os error 13)
make: *** [Makefile:3: build] Error 2
```

yeah this is the issue I am seeing with `uv pip install`

**Comment by matsonj** [comment]
the gh action to deploy isn't wokring, but bc of github perm issues i will fix that in another branch.

**Pull request merged**
