### PR TITLE
RFC: use localstack and httpfs for `make parquet`

### PR DESCRIPTION
**Pull request by petehunt**

### CODE REVIEW

**Comment by matsonj** [comment]
So this looks awesome to me. I am not super familiar with localstack so I am curious if the GitHub action (which simply builds the project) will pass.

**Comment by matsonj** [comment]
Shoot, this is failing as ```target-duckdb``` is currently broken - more [here](https://github.com/matsonj/nba-monte-carlo/issues/30).

I want to sit on this for a bit until it can build here. @petehunt Do you want to open an issue to discuss any other topics you are thinking about while we wait for this to be resolved?

**Comment by matsonj** [comment]
Ok just added back latest code from master, which means this bad boy should run now. 🤞

**Comment by matsonj** [comment]
Alright, its failing because of how things are cloned into AWS S3 (i.e. local) [here](https://github.com/matsonj/nba-monte-carlo/pull/29/commits/69d9d1bde95728217bd51d6593036b52a30c20bf#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R20). 

The fix is trivial but my brain is losing steam. Will pick this up in the AM with fresh eyes.

**Comment by petehunt** [comment]
I think my main questions here are:
1. Do we want to keep support for local parquet files on disk? Seems like a little bit of a waste since we already have `make pipeline`
2. Do we want to allow users to provide their own s3 credentials via environment variables? Or should we "marry" localstack and let users edit the steps if they want to use real S3?

**Comment by matsonj** [comment]
sheesh ok I have this "working on my machine," but I'm honestly not sure I want to merge it. Localstack is very heavy for this project (although cool as hell and exactly what I had asked for). Ok to sit on this one for a bit while I figure out how to fit it in?

**Comment by petehunt** [comment]
yeah no problem at all! can also add dagster if you want w/o localstack and just target the filesystem instead

**Comment by matsonj** [comment]
@petehunt just curious - do you usually see significant performance differences in localstack vs. "real" s3? I am seeing way slower perf on build using localstack storage vs using just on VM storage. 2min30s run time w/localstack vs 30s w/local storage. This is somewhat surprising.

**Comment by matsonj** [comment]
Yeah whenever you have time, lets chat about how tie dagster into do doing the filesystem stuff. I'm going to close this branch, as I have[ reworked how parquet is implemented](https://github.com/matsonj/nba-monte-carlo/issues/32) to make this way easier.

**Pull request closed without merging**
